<?php
namespace App;
$coders = array('Alejandro Acho',
    'Joana Börsch Peiró',
    'Sebastian Herrera',
    'Alain Robira',
    'Johana Sanchez Vallejo',
    'Eva Albors',
    'Bruna Gomez de Melo',
    'Axel Cayuela',
    'Umit Canbatur',
    'Francisco Correira',
    'Alejandro Delgado',
    'Monuir Elimalahi',
    'Sergi Oliveres',
    'Kevin Hidalgo Vivar',
    'Inna Malyutova',
    'Alberto Guerrero Martinez',
    'Jose Antonio Ortega Vailen',
    'Andrea Aguilar Picon',
    'Sofia Rocio Carballo Callegari',
    'Diego Cordoba',
    'Javier Marmol',
    'Magali Barriga',
    'Elena Carballido Marin',
    'Claudia Casals Nervaez');
